name: Playwright Tests
on:
  schedule:
    - cron: '23 23 * * *' # runs daily; adjust for 6:00 AM VN if needed
  workflow_dispatch:
   inputs:
      env:
        description: "Chọn môi trường chạy test"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod
      browser:
        description: "Chọn browser để chạy test"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - chrome
          - firefox
          - webkit
  pull_request:          
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: |
          npm ci
          npx playwright install --with-deps
      - name: Run selected Playwright test
        run: |
          echo "Running tests on ${{ github.event.inputs.env }} with browser ${{ github.event.inputs.browser }}"
          
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            npm run test:${{ github.event.inputs.env }}:all
          elif [ "${{ github.event.inputs.browser }}" = "chrome" ]; then
            npm run test:${{ github.event.inputs.env }}:chrome
          elif [ "${{ github.event.inputs.browser }}" = "firefox" ]; then
            npm run test:${{ github.event.inputs.env }}:firefox
          elif [ "${{ github.event.inputs.browser }}" = "webkit" ]; then
            npm run test:${{ github.event.inputs.env }}:webkit
          else
            echo "Invalid input"
            exit 1
          fi
        env:
          CI: true

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report
      
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Prepare combined report folder
        if: always()    
        run: |
          mkdir -p combined-report/allure
          mkdir -p combined-report/playwright
          cp -r allure-report/* combined-report/allure/ || true
          cp -r playwright-report/* combined-report/playwright/ || true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Deploy Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-report
          publish_branch: gh-pages
          force_orphan: true
